-- MySQL Script generated by MySQL Workbench
-- 07/08/15 14:28:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kniseotools
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kniseotools
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kniseotools` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `kniseotools` ;

-- -----------------------------------------------------
-- Table `kniseotools`.`kr_search_engine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kniseotools`.`kr_search_engine` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `url` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kniseotools`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kniseotools`.`user` (
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(60) NOT NULL COMMENT '',
  `email` (255) NULL COMMENT '',
  PRIMARY KEY (`username`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kniseotools`.`kr_site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kniseotools`.`kr_site` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(200) NULL COMMENT '',
  `url` VARCHAR(200) NOT NULL COMMENT '',
  `id_search_engine` INT NOT NULL COMMENT '',
  `creation_date` DATETIME NOT NULL COMMENT '',
  `run_daily` TINYINT(1) NOT NULL DEFAULT NO COMMENT '',
  `kr_search_engine_id` INT NOT NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  `user_username` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_kr_site_kr_search_engine1_idx` (`kr_search_engine_id` ASC)  COMMENT '',
  INDEX `fk_kr_site_user1_idx` (`user_id` ASC, `user_username` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kniseotools`.`kr_keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kniseotools`.`kr_keyword` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `kr_site_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_kr_keyword_kr_site1_idx` (`kr_site_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kniseotools`.`kr_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kniseotools`.`kr_note` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATETIME NOT NULL COMMENT '',
  `description` MEDIUMTEXT NOT NULL COMMENT '',
  `kr_site_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_kr_note_kr_site1_idx` (`kr_site_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kniseotools`.`kr_run`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kniseotools`.`kr_run` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATETIME NULL COMMENT '',
  `kr_site_id` INT NOT NULL COMMENT '',
  `indexed_pages` INT NULL COMMENT '',
  `pr` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_kr_run_kr_site_idx` (`kr_site_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kniseotools`.`kr_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kniseotools`.`kr_position` (
  `id` INT NOT NULL COMMENT '',
  `pos` INT NULL COMMENT '',
  `kr_run_id` INT NOT NULL COMMENT '',
  `kr_keyword_id` INT NOT NULL COMMENT '',
  `url` VARCHAR(2083) NULL COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_kr_position_kr_run1_idx` (`kr_run_id` ASC)  COMMENT '',
  INDEX `fk_kr_position_kr_keyword1_idx` (`kr_keyword_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kniseotools`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kniseotools`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `role` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_user_role_user1_idx` (`username` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
